rename estoque-api to estoque_api and Category Controller and Repository
Storage-Project/storage-project pull request #17
Opened 2022-09-20 01:02 UTC by BiancaPuertaRocha

2022-09-20 12:11 UTC, Hilst requested changes
a parte do category está ok, mas isso de renomear o `estoque-api` para `estoque_api` parece que só vai dar dor de cabeça na hora de mergear e para mexer na pipeline lá. Tem algum motivo específico para fazer isso ? @BiancaPuertaRocha

2022-09-21 11:13 UTC, BiancaPuertaRocha commented
É pq o padrão é ser com _
inclusive os namespaces nao aceitam -, eu queria ate mudar pra storage api pra ficar padrao com o app e com o resto das coisas kkk mas eu posso voltar do jeito que tava

2022-09-21 11:28 UTC, BiancaPuertaRocha commented
acho que agora nao tem nada que ja nao tivesse antes como estoque_api. EU adicionei o inicio dos testes mas é so o projeto, pode ignorar, eu percebi que foi a referencia no .csproj e resolvi mandar pra nao dar problema

2022-09-21 12:13 UTC, Hilst approved these changes
Ok. Então vamos seguir assim. Acho que os testes consigo ver o que acontece na pipe lá e consertar usando alguma flag. Acho que o padrão do dotNET é Pascal Case na real. Então teria que ser algo como EstoqueAPI

2022-09-21 12:15 UTC, BiancaPuertaRocha commented
Puts eh verdade nao é os _ 
A gente muda tudo ou deixa tudo assim ? @Hilst

2022-09-21 12:19 UTC, Hilst commented
> Puts eh verdade nao é os _ A gente muda tudo ou deixa tudo assim ? @Hilst

Acho melhor deixar assim por hora para a API. Isso parece dar alguma dor de cabeça por mudar os namespaces. Podemos corrigir no front para, pelo menos lá ficar o padrão.

2022-09-21 12:19 UTC, Hilst commented
Acho bom focarmos mais no front agora pq achei meio chato de fazer os bindings lá

2022-09-21 12:20 UTC, merged